In [2]:
pip install sdv sdmetrics

Collecting sdv
  Using cached sdv-1.37.0-py3-none-any.whl.metadata (14 kB)
Collecting sdmetrics
  Using cached sdmetrics-0.28.0-py3-none-any.whl.metadata (9.9 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Using cached boto3-1.43.23-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: botocore<2.0.0,>=1.31 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (1.36.3)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (3.0.0)
Collecting graphviz>=0.13.2 (from sdv)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=2.1.0 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (2.1.3)
Requirement already satisfied: pandas<3,>=2.2.3 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (2.2.3)
Requirement already satisfied: tqdm>=4.29 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (4.67.1)
Collecting copulas>=0.12.1 (from sdv)
  Using cached copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Using cached ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Using cached deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt>=1.18.2 (from sdv)
  Using cached rdt-1.21.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs>=4.0 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (4.3.7)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\roble\anaconda3\lib\site-packages (from sdv) (6.0.2)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Using cached botocore-1.43.23-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\roble\anaconda3\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (1.0.1)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3<2.0.0,>=1.28->sdv)
  Using cached s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\roble\anaconda3\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\roble\anaconda3\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.3.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\roble\anaconda3\lib\site-packages (from pandas<3,>=2.2.3->sdv) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\roble\anaconda3\lib\site-packages (from pandas<3,>=2.2.3->sdv) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\roble\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: scikit-learn>=1.5.2 in c:\users\roble\anaconda3\lib\site-packages (from sdmetrics) (1.6.1)
Requirement already satisfied: scipy>=1.14.1 in c:\users\roble\anaconda3\lib\site-packages (from sdmetrics) (1.15.3)
Requirement already satisfied: plotly>=5.19.0 in c:\users\roble\anaconda3\lib\site-packages (from sdmetrics) (5.24.1)
Collecting torch>=2.6.0 (from ctgan>=0.11.1->sdv)
  Using cached torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\roble\anaconda3\lib\site-packages (from plotly>=5.19.0->sdmetrics) (9.0.0)
Requirement already satisfied: packaging in c:\users\roble\anaconda3\lib\site-packages (from plotly>=5.19.0->sdmetrics) (24.2)
Requirement already satisfied: Faker!=37.11.0,>=17 in c:\users\roble\anaconda3\lib\site-packages (from rdt>=1.18.2->sdv) (40.21.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\roble\anaconda3\lib\site-packages (from scikit-learn>=1.5.2->sdmetrics) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\roble\anaconda3\lib\site-packages (from scikit-learn>=1.5.2->sdmetrics) (3.5.0)
Requirement already satisfied: filelock in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (4.12.2)
Requirement already satisfied: setuptools<82 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\roble\anaconda3\lib\site-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\roble\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.6.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: colorama in c:\users\roble\anaconda3\lib\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\roble\anaconda3\lib\site-packages (from jinja2->torch>=2.6.0->ctgan>=0.11.1->sdv) (3.0.2)
Using cached sdv-1.37.0-py3-none-any.whl (206 kB)
Using cached boto3-1.43.23-py3-none-any.whl (140 kB)
Downloading botocore-1.43.23-py3-none-any.whl (15.1 MB)
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
    --------------------------------------- 0.3/15.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   - -------------------------------------- 0.5/15.1 MB 30.6 kB/s eta 0:07:59
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 0.8/15.1 MB 36.4 kB/s eta 0:06:35
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   -- ------------------------------------- 1.0/15.1 MB 49.7 kB/s eta 0:04:44
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   --- ------------------------------------ 1.3/15.1 MB 60.0 kB/s eta 0:03:51
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.6/15.1 MB 65.3 kB/s eta 0:03:28
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47
   ---- ----------------------------------- 1.8/15.1 MB 58.9 kB/s eta 0:03:47

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.19.0 requires botocore<1.36.4,>=1.36.0, but you have botocore 1.43.23 which is incompatible.

   ---- ---------------------------------- 15.5/123.0 MB 143.4 kB/s eta 0:12:30
   ---- ---------------------------------- 15.5/123.0 MB 143.4 kB/s eta 0:12:30
   ---- ---------------------------------- 15.5/123.0 MB 143.4 kB/s eta 0:12:30
   ---- ---------------------------------- 15.5/123.0 MB 143.4 kB/s eta 0:12:30
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ---- ---------------------------------- 15.7/123.0 MB 144.3 kB/s eta 0:12:24
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.0/123.0 MB 141.5 kB/s eta 0:12:37
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.3/123.0 MB 131.4 kB/s eta 0:13:33
   ----- --------------------------------- 16.5/123.0 MB 124.2 kB/s eta 0:14:18
   ----- --------------------------------- 16.5/123.0 MB 124.2 kB/s eta 0:14:18
   ----- --------------------------------- 16.5/123.0 MB 124.2 kB/s eta 0:14:18
   ----- --------------------------------- 16.8/123.0 MB 126.5 kB/s eta 0:14:00
   ----- --------------------------------- 16.8/123.0 MB 126.5 kB/s eta 0:14:00
   ----- --------------------------------- 16.8/123.0 MB 126.5 kB/s eta 0:14:00
   ----- --------------------------------- 16.8/123.0 MB 126.5 kB/s eta 0:14:00
   ----- --------------------------------- 16.8/123.0 MB 126.5 kB/s eta 0:14:00
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.3/123.0 MB 137.4 kB/s eta 0:12:50
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.6/123.0 MB 133.1 kB/s eta 0:13:13
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 17.8/123.0 MB 131.2 kB/s eta 0:13:22
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.1/123.0 MB 123.5 kB/s eta 0:14:10
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.4/123.0 MB 128.1 kB/s eta 0:13:37
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.6/123.0 MB 113.4 kB/s eta 0:15:21
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ----- --------------------------------- 18.9/123.0 MB 106.0 kB/s eta 0:16:23
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.1/123.0 MB 97.8 kB/s eta 0:17:43
   ------ --------------------------------- 19.4/123.0 MB 96.2 kB/s eta 0:17:58
   ------ --------------------------------- 19.4/123.0 MB 96.2 kB/s eta 0:17:58
   ------ --------------------------------- 19.4/123.0 MB 96.2 kB/s eta 0:17:58
   ------ --------------------------------- 19.7/123.0 MB 96.8 kB/s eta 0:17:48
   ------ --------------------------------- 19.7/123.0 MB 96.8 kB/s eta 0:17:48
   ------ --------------------------------- 19.7/123.0 MB 96.8 kB/s eta 0:17:48
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 19.9/123.0 MB 97.6 kB/s eta 0:17:36
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.4/123.0 MB 90.8 kB/s eta 0:18:50
   ------ --------------------------------- 20.7/123.0 MB 91.7 kB/s eta 0:18:36
   ------ --------------------------------- 20.7/123.0 MB 91.7 kB/s eta 0:18:36
   ------ --------------------------------- 20.7/123.0 MB 91.7 kB/s eta 0:18:36
   ------ --------------------------------- 20.7/123.0 MB 91.7 kB/s eta 0:18:36
   ------ --------------------------------- 20.7/123.0 MB 91.7 kB/s eta 0:18:36
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.0/123.0 MB 97.0 kB/s eta 0:17:32
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38
   ------ --------------------------------- 21.2/123.0 MB 96.3 kB/s eta 0:17:38

# Libreria SDV
 
*Autor: Alumno*

*Fecha: 04 de Junio*

In [13]:
#Importamos librerías
import pandas as pd
import numpy as np
import random

In [8]:
import sdv #Generar datos sinteticos
import sdmetrics #Evaluar la calidad de los datos generados

from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

In [9]:
from sdmetrics.reports.single_table import QualityReport

In [10]:
print ("SDV: ", sdv.__version__)

SDV:  1.37.0

In [14]:
#Creamos un Dataset (original) que servira como fuente para crear los datos sinteticos
dfClientes = pd.DataFrame(
    {
        "cliente_id" : [1,2,3,4,5,6,7,8,9,10],
        "edad" : [23,33,43,28,53,43,56,56,65,40],
        "ingreso_mensual" : [25000,15000,20000,10000,5000,17000,30000,12000,35000,7500],
        "ciudad" : ["Veracruz","Cordoba","Paso_del_macho","Amatlan","Fortin","Cuitlahuac","Yanga","Peluche","Orizaba","Potrero"]
    }
)

In [16]:
dfClientes.head()

   cliente_id  edad  ingreso_mensual          ciudad
0           1    23            25000        Veracruz
1           2    33            15000         Cordoba
2           3    43            20000  Paso_del_macho
3           4    28            10000         Amatlan
4           5    53             5000          Fortin

In [17]:
#Definir los metadatos
metadata = SingleTableMetadata()

In [18]:
metadata.detect_from_dataframe(
    data = dfClientes
)

In [21]:
metadata.to_dict()

{'columns': {'cliente_id': {'sdtype': 'id'},
  'edad': {'sdtype': 'numerical'},
  'ingreso_mensual': {'sdtype': 'numerical'},
  'ciudad': {'sdtype': 'categorical'}},
 'primary_key': 'cliente_id',
 'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1'}

In [23]:
#Guardamos el metadata en un archivo JSON
metadata.save_to_json(
    "df_Clientes_metadata.json"
)

In [24]:
#Entrenamos el modelo para generar los datos sintéticos
synthesizer = GaussianCopulaSynthesizer(
    metadata
)

C:\Users\roble\anaconda3\Lib\site-packages\sdv\single_table\base.py:182: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)

In [25]:
# Entrenamiento
synthesizer.fit(
    dfClientes
)

In [26]:
#Generamos los datos sintéticos
clientes_sinteticos = synthesizer.sample (
    num_rows=100
)

In [27]:
clientes_sinteticos.head()

   cliente_id  edad  ingreso_mensual   ciudad
0    16169768    60            16560  Orizaba
1     4918803    36            31997   Fortin
2     1900081    36            19348    Yanga
3      531516    29            28544  Peluche
4    10211768    50            29740  Orizaba

In [28]:
clientes_sinteticos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cliente_id       100 non-null    int64
 1   edad             100 non-null    int64
 2   ingreso_mensual  100 non-null    int64
 3   ciudad           100 non-null    object
dtypes: int64(3), object(1)
memory usage: 3.3+ KB

In [29]:
clientes_sinteticos.describe(include="all")

          cliente_id        edad  ingreso_mensual   ciudad
count   1.000000e+02  100.000000       100.000000      100
unique           NaN         NaN              NaN       10
top              NaN         NaN              NaN  Orizaba
freq             NaN         NaN              NaN       14
mean    8.532170e+06   43.020000     21598.970000      NaN
std     4.687773e+06   11.983136      8631.731949      NaN
min     4.660500e+04   28.000000      6037.000000      NaN
25%     5.008268e+06   33.000000     14426.250000      NaN
50%     8.656048e+06   41.000000     20652.000000      NaN
75%     1.256688e+07   53.000000     29364.000000      NaN
max     1.661551e+07   65.000000     34856.000000      NaN

In [30]:
#DataFrame contaminado
dfClientesGIGO = clientes_sinteticos.copy()

In [31]:
#Colocar edades imposibles
indices = random.sample(list(dfClientesGIGO.index),5)

In [33]:
dfClientesGIGO.loc[indices, "edad"] = -5

In [34]:
#Introducir valores duplicados
duplicados = dfClientesGIGO.sample(10,random_state=42)

In [35]:
dfClientesGIGO = pd.concat([dfClientesGIGO, duplicados], ignore_index=True)

In [36]:
#Verificamos valores nulos
dfClientesGIGO.duplicated().sum()

np.int64(10)

In [37]:
dfClientesGIGO.describe(include="all")

          cliente_id        edad  ingreso_mensual   ciudad
count   1.100000e+02  110.000000       110.000000      110
unique           NaN         NaN              NaN       10
top              NaN         NaN              NaN  Cordoba
freq             NaN         NaN              NaN       16
mean    8.614045e+06   39.118182     21178.954545      NaN
std     4.775996e+06   15.686570      8625.759095      NaN
min     4.660500e+04   -5.000000      6037.000000      NaN
25%     4.948624e+06   30.000000     14178.750000      NaN
50%     8.956428e+06   39.000000     19563.000000      NaN
75%     1.274153e+07   49.750000     29004.750000      NaN
max     1.661551e+07   65.000000     34856.000000      NaN

In [38]:
#Generar el reporte
report = QualityReport()

In [41]:
report.generate (
    real_data = dfClientes,
    synthetic_data = dfClientesGIGO,
    metadata = metadata.to_dict()
)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 4/4 [00:00<00:00, 413.27it/s]|
Column Shapes Score: 80.3%

(2/2) Evaluating Column Pair Trends: |██████████| 6/6 [00:00<00:00, 133.29it/s]|
Column Pair Trends Score: 9.09%

Overall Score (Average): 44.7%